enum rfwTypes {
  SET_RFW_PAGE = 'SET_RFW_PAGE',

  RFWS_DATA = 'RFWS_DATA',
  RFWS_DATA_FULFILLED = 'RFWS_DATA_FULFILLED',
  RFWS_DATA_REJECTED = 'RFWS_DATA_REJECTED',
  RFWS_DATA_PENDING = 'RFWS_DATA_PENDING',

  RFW_DATA = 'RFW_DATA',
  RFW_DATA_FULFILLED = 'RFW_DATA_FULFILLED',
  RFW_DATA_REJECTED = 'RFW_DATA_REJECTED',
  RFW_DATA_PENDING = 'RFW_DATA_PENDING',

  RFW_WORKER_REQUEST = 'RFW_WORKER_REQUEST',
  RFW_WORKER_REQUEST_FULFILLED = 'RFW_WORKER_REQUEST_FULFILLED',
  RFW_WORKER_REQUEST_REJECTED = 'RFW_WORKER_REQUEST_REJECTED',
  RFW_WORKER_REQUEST_PENDING = 'RFW_WORKER_REQUEST_PENDING',

  RFW_MILESTONE_CLAIM = 'RFW_MILESTONE_CLAIM',
  RFW_MILESTONE_CLAIM_FULFILLED = 'RFW_MILESTONE_CLAIM_FULFILLED',
  RFW_MILESTONE_CLAIM_REJECTED = 'RFW_MILESTONE_CLAIM_REJECTED',
  RFW_MILESTONE_CLAIM_PENDING = 'RFW_MILESTONE_CLAIM_PENDING',

  RFW_FETCH_TAGS = 'RFW_FETCH_TAGS',
  RFW_FETCH_TAGS_FULFILLED = 'RFW_FETCH_TAGS_FULFILLED',
  RFW_FETCH_TAGS_REJECTED = 'RFW_FETCH_TAGS_REJECTED',
  RFW_FETCH_TAGS_PENDING = 'RFW_FETCH_TAGS_PENDING',
}

export default rfwTypes;
