"""Replace payout_percent withou payout_amount

Revision ID: 0bc44b78f4d7
Revises: c1e2802ce619
Create Date: 2019-07-01 18:31:41.854971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bc44b78f4d7'
down_revision = '460f8e5624ae'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('milestone', sa.Column('payout_amount', sa.String(length=255), nullable=False, server_default='0'))

    # Removes default of zero, doesn't actually calculate amount
    op.alter_column('milestone', 'payout_amount', server_default=None)

    op.drop_column('milestone', 'payout_percent')
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('milestone', sa.Column('payout_percent', sa.VARCHAR(length=255), autoincrement=False, nullable=False, server_default='0'))

    # Removes default of zero, doesn't actually calculate amount
    op.alter_column('milestone', 'payout_percent', server_default=None)

    op.drop_column('milestone', 'payout_amount')
    # ### end Alembic commands ###
