"""Azimuth points

Revision ID: 460f8e5624ae
Revises: f592c54e67cc
Create Date: 2019-06-27 15:16:10.818413

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '460f8e5624ae'
down_revision = 'f592c54e67cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('azimuth_point',
    sa.Column('point', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('point')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('azimuth_point')
    # ### end Alembic commands ###
