"""empty message

Revision ID: 6b89fae381cb
Revises: 474eaaf7ff0c
Create Date: 2019-07-10 09:52:54.477428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b89fae381cb'
down_revision = '474eaaf7ff0c'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('proposal', 'private',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('proposal', 'private',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
