"""RFW adjustments

Revision ID: ce643e3a7575
Revises: 0bc44b78f4d7
Create Date: 2019-07-01 19:23:15.079995

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ce643e3a7575'
down_revision = '0bc44b78f4d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rfw_milestone_claim_update')
    op.drop_column('rfw_milestone', 'closed')
    op.add_column('rfw_milestone_claim', sa.Column('stage_url', sa.String(), nullable=False, server_default=''))

    # Removes default of empty string
    op.alter_column('rfw_milestone_claim', 'stage_url', server_default=None)

    op.drop_column('rfw_milestone_claim', 'reward')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rfw_milestone_claim', sa.Column('reward', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('rfw_milestone_claim', 'stage_url')
    op.add_column('rfw_milestone', sa.Column('closed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_table('rfw_milestone_claim_update',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
                    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
                    sa.Column('url', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
                    sa.Column('claim_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['claim_id'], ['rfw_milestone_claim.id'],
                                            name='rfw_milestone_claim_update_claim_id_fkey'),
                    sa.PrimaryKeyConstraint('id', name='rfw_milestone_claim_update_pkey')
                    )
    # ### end Alembic commands ###
