"""Proposal follow & private

Revision ID: d4dfc72009c8
Revises: ce643e3a7575
Create Date: 2019-07-02 16:45:45.352567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4dfc72009c8'
down_revision = 'ce643e3a7575'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proposal_follower',
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('proposal_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['proposal_id'], ['proposal.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
                    )
    op.add_column('proposal', sa.Column('private', sa.Boolean(), server_default=sa.text('FALSE'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proposal', 'private')
    op.drop_table('proposal_follower')
    # ### end Alembic commands ###
