"""rfw and friends

Revision ID: f592c54e67cc
Revises: c4db14a99db2
Create Date: 2019-06-18 17:16:05.432404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f592c54e67cc'
down_revision = 'c4db14a99db2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rfw',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('date_created', sa.DateTime(), nullable=True),
                    sa.Column('title', sa.String(length=255), nullable=False),
                    sa.Column('brief', sa.String(length=255), nullable=False),
                    sa.Column('content', sa.Text(), nullable=False),
                    sa.Column('status', sa.String(length=255), nullable=False),
                    sa.Column('status_change_date', sa.DateTime(), nullable=True),
                    sa.Column('category', sa.String(length=255), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('tag',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('text', sa.String(length=255), nullable=False),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('color', sa.String(length=255), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('rfw_milestone',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('index', sa.Integer(), nullable=False),
                    sa.Column('date_created', sa.DateTime(), nullable=True),
                    sa.Column('title', sa.String(length=255), nullable=False),
                    sa.Column('content', sa.Text(), nullable=False),
                    sa.Column('effort_from', sa.BigInteger(), nullable=False),
                    sa.Column('effort_to', sa.BigInteger(), nullable=False),
                    sa.Column('bounty', sa.BigInteger(), nullable=False),
                    sa.Column('closed', sa.Boolean(), nullable=True),
                    sa.Column('rfw_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['rfw_id'], ['rfw.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('rfw_worker',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('date_created', sa.DateTime(), nullable=True),
                    sa.Column('status', sa.String(length=255), nullable=False),
                    sa.Column('status_message', sa.String(), nullable=False),
                    sa.Column('status_change_date', sa.DateTime(), nullable=True),
                    sa.Column('rfw_id', sa.Integer(), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['rfw_id'], ['rfw.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('tag_association',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('rfw_id', sa.Integer(), nullable=True),
                    sa.Column('tag_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['rfw_id'], ['rfw.id'], ),
                    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('rfw_milestone_claim',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('date_created', sa.DateTime(), nullable=True),
                    sa.Column('stage', sa.String(length=255), nullable=False),
                    sa.Column('stage_message', sa.String(), nullable=False),
                    sa.Column('stage_change_date', sa.DateTime(), nullable=False),
                    sa.Column('reward', sa.BigInteger(), nullable=True),
                    sa.Column('worker_id', sa.Integer(), nullable=True),
                    sa.Column('milestone_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['milestone_id'], ['rfw_milestone.id'], ),
                    sa.ForeignKeyConstraint(['worker_id'], ['rfw_worker.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('rfw_milestone_claim_update',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('date_created', sa.DateTime(), nullable=True),
                    sa.Column('message', sa.Text(), nullable=False),
                    sa.Column('url', sa.String(length=255), nullable=False),
                    sa.Column('claim_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['claim_id'], ['rfw_milestone_claim.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rfw_milestone_claim_update')
    op.drop_table('rfw_milestone_claim')
    op.drop_table('tag_association')
    op.drop_table('rfw_worker')
    op.drop_table('rfw_milestone')
    op.drop_table('tag')
    op.drop_table('rfw')
    # ### end Alembic commands ###
